# This file contains values from Cookiecutter

default_context:
  project_name: "aix"
  project_description: "AIXplained"
  organization: "VarianceXplained"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "variancexplained"
  email: "john@variancexplained.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
